# Generated by Django 4.2 on 2023-06-08 11:06

import apps.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', validators=[apps.photos.validators.validate_file_size])),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
